/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_reid_qqvoice_VoiceTools */

#ifndef _Included_com_reid_qqvoice_VoiceTools
#define _Included_com_reid_qqvoice_VoiceTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_reid_qqvoice_VoiceTools
 * Method:    changeVoice
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_reid_qqvoice_VoiceTools_changeVoice
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
